export const defaultTheme = {
  colorForBlackText: "#333333",
  colorWhite: "#ffffff",
  colorGray: "#f6f6f6",
  colorForLightBackground: "#fff6d9",
  colorForDarkBackground: "#ffeead",
  colorForNewIcon: "#ffb334",
  colorForSoftIcon: "#7fc92e",
  colorForButton: "#ff732b",
  colorForButtonHover: "f35714",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  footerHeight: "80px",
  pageWidth: "1280px",
};
